# Generated by Django 5.2.5 on 2025-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cable_length_m',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Approximate run in meters', max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='charger_power_kw',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='e.g. 7.4, 11, 22, 50', max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='charger_type',
            field=models.CharField(choices=[('ac', 'AC Charger'), ('dc', 'DC Fast Charger')], default='ac', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='civil_work',
            field=models.BooleanField(default=False, help_text='Trenching, core drilling, base/stand, etc.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earthing_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='interlock_removal',
            field=models.BooleanField(default=False, help_text='Remove/adjust interlock if present'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mounting_type',
            field=models.CharField(choices=[('wall', 'Wall-mounted'), ('pedestal', 'Pedestal/Stand')], default='wall', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phase',
            field=models.CharField(choices=[('single', 'Single-phase'), ('three', 'Three-phase')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='preferred_install_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rcd_type',
            field=models.CharField(choices=[('type_a', 'Type A'), ('type_b', 'Type B'), ('rcbo', 'RCBO'), ('other', 'Other/Consult')], default='type_a', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='site_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='site_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supply_type',
            field=models.CharField(choices=[('existing', 'Use existing supply'), ('new_circuit', 'New dedicated circuit'), ('upgrade', 'Supply upgrade required')], default='existing', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='surge_protection',
            field=models.BooleanField(default=True),
        ),
    ]
